name: accountingapp
description: A Flutter accounting application integrated with MetaMask.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  provider: ^6.0.0
  http: ^0.13.4
  web3dart: ^2.5.3
  firebase_core: ^2.0.0
  cloud_firestore: ^4.0.0
  fl_chart: ^0.65.0
  font_awesome_flutter: ^10.1.0
  uuid: ^3.0.6
  flutter_dotenv: ^5.1.0
  intl: ^0.18.0
  logger: ^1.1.0
  shared_preferences: ^2.0.15
  walletconnect_flutter_v2: ^2.1.4
  qr_flutter: ^4.0.0
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/TransactionStorageABI.json
    
